### ISSUE TITLE
Замечания по работе

### ISSUE THREAD

**Issue by AndriiLitvin** [Sammersss/Sammersss.github.io#1]
Визуально http://joxi.ru/4AkegKpfvXMnmq:
1)Размер Фото + нет border-radius на ней
2)нет border-radius на блоке с контентом, на самой визитке.

Код:
1) Название классов  css должны говорить сами за себя. чтоб без контента там можно было понять что там должно быть, и желательно названия должны быть на английском а не латиницей.

Должно быть максимально идентичное этому макету https://raw.githubusercontent.com/goit-fe/markup_fe2o/master/lesson_01/homework1.png

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ

**Comment by AndriiLitvin** [comment]
Вместо < hr > сделай блоку border-bottom

**Comment by Sammersss** [comment]
готово
