### ISSUE TITLE
Замечание экзамен js

### ISSUE THREAD

**Issue by AndriiLitvin** [Sammersss/Sammersss.github.io#21]
вообще практически не к чему придраться)) но я нашел)
1,
на ие не работает вот эта плитка http://joxi.ru/gmvgpyqtxzjGR2

2.
все внешние скрипты нужно(кроме ИЕ) конкатенировать и минифицировать и подключить vendor.min.js

по фиксь и будет тебе счастье)

**Comment by Sammersss** [comment]
Исправил

**Comment by AndriiLitvin** [comment]
аа. вот еще штука 
![image](https://cloud.githubusercontent.com/assets/13675947/14042521/51b81d62-f283-11e5-8b95-ba1617cfc52f.png)
у dist должен быть индекс. там же лежат готовые файли на продакшн.

ЗАЧЕТ

**Comment by AndriiLitvin** [comment]
![image](https://cloud.githubusercontent.com/assets/13675947/14142438/5ddec2bc-f68e-11e5-8a79-8c961b5afc93.png)
я от своих слов не отказываюсь у тебя зачет та как это мой бок.
тут нужно чтоб при первой загрузки были все картинки рамдомные

**Comment by Sammersss** [comment]
поправил первую загрузку

**Comment by AndriiLitvin** [comment]
не совсем. нужно как у него http://speariv35.github.io/GoIT/javascript/exam1/build/
чтоб при каждой загрузке разные картинки. просто в тз так написано.

**Comment by Sammersss** [comment]
сделал рандомную загрузку картинок

**Comment by AndriiLitvin** [comment]
отценрируй а то что то полезло либо тогда не доглядел
![image](https://cloud.githubusercontent.com/assets/13675947/14173281/9873f610-f745-11e5-8913-735e4d82e320.png)

**Comment by Sammersss** [comment]
поменял fancybox

**Comment by AndriiLitvin** [comment]
Все ок)
