### ISSUE TITLE
Замечания по работе 5.1 cadastre

### ISSUE THREAD

**Issue by AndriiLitvin** [Sammersss/Sammersss.github.io#4]
http://joxi.ru/gmvgpyqtpnv32a
сделать на весь экран

**Comment by Sammersss** [comment]
исправил

**Comment by AndriiLitvin** [comment]
http://joxi.ru/GrqgjnLt1j5k2z -при ресайзе окна вот что . wrapper должен быть фиксированой ширины + поцепи фон на боди, и в хедера и в контента должен бЫть отдельно wrapper. так как у хедера фон должен быть на всю страницу на любых экранах

**Comment by Sammersss** [comment]
исправил, надеюсь что правильно понял что нужно сделать
1 обернуть  в отдельные  врапперы
2 перенести фон в боди 
3 контенту и хедеру фиксированную ширину
4 фон хедера на всю страницу

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
