### ISSUE TITLE
Замечания по экзамену 7-9

### ISSUE THREAD

**Issue by AndriiLitvin** [Sammersss/Sammersss.github.io#7]
## 1. Ширина 960 http://joxi.ru/bmoVE3WuMNqVXr

1)нужны отступы
2)6)это навигация там показывается активный слайд
3)text-shadow (практически по всему макету)
4)там градиент
5)text-shadow
7) стрелки не влазят. там показано на шире. там нужно чтоб адаптивно оно было.
## 2. Экран 768 http://joxi.ru/8AnVER6uq1kbjA

1) не влазят стрелки
2) ширина третьего блока с текстом такая же как и у второго блока
3) предыдущие замечания. 
## 3. Экран 480 http://joxi.ru/a2XQzB3Hy0o0LA

1) стрелочки +  предыдущие замечания
## 4. Экран 320 http://joxi.ru/MAjlEL1FvRg4Rm

1)текст полез
2)отцентрируй +  предыдущие замечания

**Comment by AndriiLitvin** [comment]
у тебя не совсем правильно медиа квери прописаны. сначала идут большие экраны а потом меньше и меньше. + судя по вчерашниму вебинару то там такие экраны
320-479 480-767 768-959 и 960+

**Comment by Sammersss** [comment]
исправил замечания.

а по поводу  
"у тебя не совсем правильно медиа квери прописаны. сначала идут большие экраны а потом меньше и меньше. + судя по вчерашниму вебинару то там такие экраны
320-479 480-767 768-959 и 960+"

я не указывал жесткие рамки потому , что хотел наследования параметров , 
чтоб изменять только некоторые свойства , а остальные наследовались. 
если указать 768Х959 , то наследования не будет 
и нужно повторять уже ранее прописанные параметры, а зачем если они одинаковые?
кроме того говорили о mobile first, я полагал, что так и нужно в медиа записывать - 
сперва мелкие екраины.
и на вебинаре Олег говорил что можно сперва 320, потом 480 .... это на 7мин. 35 сек ведео
https://youtu.be/UUsj9Q6y1CY?t=7m35s

**Comment by AndriiLitvin** [comment]
## Экран 960 http://joxi.ru/xAe0gQ1sYJwgN2

1)бекграунд вылазит за ширину 960
2)паддинги больше padding: 32px 43px 32px 38px;
3)отступ большой
4)5) почему картинки можно ж тень сделать просто через css

## Экран 768 http://joxi.ru/Y2L0zPXsnwZGj2

1)бекграунд вылазит за ширину
2)3) вот картинки и вылезли) меньшая ширина

## Экран 480 http://joxi.ru/RmzkEJqFWXBNx2

## Экран 320 http://joxi.ru/Y2L0zPXsnwZWO2

**Comment by Sammersss** [comment]
исправил

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
